"""Add missing columns

Revision ID: 9630ee6c90fa
Revises: 
Create Date: 2025-09-21 18:01:25.066718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9630ee6c90fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Complaints', sa.Column('category', sa.String(), nullable=True))
    op.add_column('Complaints', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('Complaints', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('Complaints', sa.Column('feedback_rating', sa.Float(), nullable=True))
    op.add_column('Complaints', sa.Column('feedback_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Complaints', 'feedback_comment')
    op.drop_column('Complaints', 'feedback_rating')
    op.drop_column('Complaints', 'assigned_to')
    op.drop_column('Complaints', 'media_url')
    op.drop_column('Complaints', 'category')
    # ### end Alembic commands ###
